'use client';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faArrowDown,
  faArrowLeft,
  faArrowUp,
  faArrowRight,
  faArrowRotateRight,
  faBath,
  faBed,
  faBell,
  faBookOpen,
  faBullseye,
  faBuilding,
  faCamera,
  faCheck,
  faChevronDown,
  faChevronRight,
  faCirclePlay,
  faCircleInfo,
  faClock,
  faCouch,
  faDroplet,
  faDoorOpen,
  faEnvelope,
  faEye,
  faFileLines,
  faFire,
  faGear,
  faHeart,
  faHouse,
  faImage,
  faKey,
  faKitMedical,
  faLightbulb,
  faListCheck,
  faMagnifyingGlass,
  faMoneyBill,
  faPause,
  faPencil,
  faPeopleGroup,
  faPerson,
  faPersonCircleCheck,
  faPersonShelter,
  faPlus,
  faRightFromBracket,
  faShieldHalved,
  faShower,
  faSliders,
  faStar,
  faTrash,
  faUmbrellaBeach,
  faUtensils,
  faUser,
  faUserGroup,
  faWifi,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

const icons = {
  arrowDown: faArrowDown,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  arrowRotateRight: faArrowRotateRight,
  arrowUp: faArrowUp,
  bath: faBath,
  bed: faBed,
  bell: faBell,
  bookOpen: faBookOpen,
  bullseye: faBullseye,
  building: faBuilding,
  camera: faCamera,
  check: faCheck,
  chevronDown: faChevronDown,
  chevronRight: faChevronRight,
  clock: faClock,
  circlePlay: faCirclePlay,
  couch: faCouch,
  droplet: faDroplet,
  doorOpen: faDoorOpen,
  envelope: faEnvelope,
  eye: faEye,
  fileLines: faFileLines,
  fire: faFire,
  gear: faGear,
  heart: faHeart,
  house: faHouse,
  image: faImage,
  info: faCircleInfo,
  key: faKey,
  kitMedical: faKitMedical,
  lightbulb: faLightbulb,
  listCheck: faListCheck,
  magnifyingGlass: faMagnifyingGlass,
  moneyBill: faMoneyBill,
  pause: faPause,
  pencil: faPencil,
  peopleGroup: faPeopleGroup,
  person: faPerson,
  personCircleCheck: faPersonCircleCheck,
  personShelter: faPersonShelter,
  plus: faPlus,
  rightFromBracket: faRightFromBracket,
  shield: faShieldHalved,
  shower: faShower,
  sliders: faSliders,
  star: faStar,
  trash: faTrash,
  umbrellaBeach: faUmbrellaBeach,
  utensils: faUtensils,
  user: faUser,
  userGroup: faUserGroup,
  wifi: faWifi,
  xmark: faXmark,
} satisfies Record<string, IconDefinition>;

export type AppIconName = keyof typeof icons;

interface AppIconProps {
  name: AppIconName;
  className?: string;
  title?: string;
}

export default function AppIcon({ name, className, title }: AppIconProps) {
  return <FontAwesomeIcon icon={icons[name]} className={className} title={title} aria-hidden={!title} />;
}
